on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

name: Publish JS library to gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # Starting with Ubuntu 23+, a security feature prevents running Puppeteer
    # by default. It needs to be disabled. Using the "easiest" option, see:
    # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
    # https://github.com/puppeteer/puppeteer/pull/13196/files
    - name: Disable AppArmor
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Run tests
      run: |
        npm ci
        npm test

    - name: Publish one lib per tag to gh-pages branch
      run: |
        git config user.name "i-slide-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        node tools/publish-lib.js
        git push origin gh-pages:gh-pages
